targets:
  $default:
    sources:
      - lib/**
      - lib/assets/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/assets"
          output_folder: "lib/api"
