name: geo_profiles_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0
  retrofit: ^4.0.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  chopper: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.0
  retrofit_generator: ^9.2.0
  json_serializable: ^6.6.0
  flutter_lints: ^5.0.0
  swagger_dart_code_generator: ^3.0.1
  chopper_generator: ^8.1.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/api.swagger.json


